name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Post-deploy commands (git pull, build & pm2 restart)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASS }}
          script: |
            cd ~/eanathos/puzzle-multiplayer
            git pull
            npm install
            npm run build
            pm2 restart puzzle-multiplayer || PORT=3005 pm2 start server/src/index.ts --name puzzle-multiplayer --interpreter ./node_modules/.bin/tsx
            pm2 save
